name: Build Arm32

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker run --name ubuntu12-arm32-kernel -dit i386/ubuntu:12.04 bash

    - name: Update sources.list
      run: |
        docker exec ubuntu12-arm32-kernel bash -c "sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/old-releases.ubuntu.com/g' /etc/apt/sources.list"

    - name: Install
      run: |
        docker exec ubuntu12-arm32-kernel bash -c "
          apt-get update &&
          apt-get install -y build-essential gcc-arm-linux-gnueabihf bc u-boot-tools libncurses5-dev flex bison python openssl libssl-dev &&
          apt-get clean
        "

    - name: Copy Source
      run: |
        docker cp . ubuntu12-arm32-kernel:/kernel-source

    - name: Build Kernel
      run: |
        docker exec ubuntu12-arm32-kernel bash -c "
          cd /kernel-source &&
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- clean &&
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- msm8916_defconfig &&
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)
        "

    - name: Retrieve
      run: |
        docker cp ubuntu12-arm32-kernel:/kernel-source/arch/arm/boot/zImage ./zImage

    - name: Clean up
      run: |
        docker rm -f ubuntu12-arm32-kernel

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-arm32-kernel
        path: zImage