name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker with Debian 7
      run: |
        docker pull debian:7
        docker run --rm -d --name kernel-build debian:7 sleep infinity

    - name: Install dependencies in Docker
      run: |
        docker exec kernel-build bash -c "echo 'deb http://archive.debian.org/debian/ wheezy main' > /etc/apt/sources.list"
        docker exec kernel-build bash -c "echo 'deb http://archive.debian.org/debian-security/ wheezy/updates main' >> /etc/apt/sources.list"
        docker exec kernel-build apt-get update
        docker exec kernel-build apt-get install -y \
          build-essential \
          gcc-4.9 \
          g++-4.9 \
          make \
          libncurses5-dev \
          libssl-dev \
          bc \
          wget \
          curl \
          git \
          python \
          bison \
          flex \
          libelf-dev \
          libssl-dev \
          openssl

    - name: Install Linaro GCC Toolchain (ARM-EABI-4.9)
      run: |
        docker exec kernel-build apt-get install -y gcc-arm-linux-gnueabi
        docker exec kernel-build ln -s /usr/bin/gcc-4.9 /usr/bin/arm-eabi-gcc

    - name: Copy Source
      run: |
        docker cp . kernel-build:/kernel

    - name: Set up kernel configuration
      run: |
        docker exec kernel-build cd /kernel && make ARCH=arm CROSS_COMPILE=arm-eabi- msm8916_defconfig

    - name: Build the kernel
      run: |
        docker exec kernel-build cd /kernel && make ARCH=arm CROSS_COMPILE=arm-eabi- -j$(nproc)

    - name: Archive the built kernel
      run: |
        docker exec kernel-build cp /kernel/arch/arm/boot/zImage /kernel_build/zImage
        docker cp kernel-build:/kernel_build/zImage ./zImage

    - name: Upload built kernel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-zImage
        path: ./zImage

    - name: Clean up Docker container
      run: docker rm -f kernel-build
